exports.course = require('./course')
exports.questionBank = require('./questionBank')
exports.knowledge = require('./knowledge')
exports.headline = require('./headline')
exports.administrator = require('./administrator')
exports.certificate = require('./certificate')
exports.test = require('./test')
